[package]
name = "cloudinary"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.66"
chrono = "0.4.22"
itertools = "0.10.5"
mime = "0.3.16"
paste = "1.0.9"
reqwest = { version = "0.11.18", features=["json", "multipart", "stream"]}
serde = { version  = "1.0.147", features = ["derive"] }
serde_json = "1.0.87"
sha1 = "0.10.5"
tokio = {version = "1.28.2", features=["full"]}
tokio-util = "0.7.4"
log = "0.4.14"
openssl = { version = "0.10", features = ["vendored"] }
