use std::fmt::Display;
/// CSS named colors V4.
/// <https://www.w3.org/TR/css-color-4/#named-colors>
#[derive(Debug, Clone)]
pub enum NamedColor {
    AliceBlue,
    AntiqueWhite,
    Aqua,
    Aquamarine,
    Azure,
    Beige,
    Bisque,
    Black,
    BlanchedAlmond,
    Blue,
    BlueViolet,
    Brown,
    BurlyWood,
    CadetBlue,
    Chartreuse,
    Chocolate,
    Coral,
    CornflowerBlue,
    Cornsilk,
    Crimson,
    Cyan,
    DarkBlue,
    DarkCyan,
    DarkGoldenRod,
    DarkGray,
    DarkGrey,
    DarkGreen,
    DarkKhaki,
    DarkMagenta,
    DarkOliveGreen,
    DarkOrange,
    DarkOrchid,
    DarkRed,
    DarkSalmon,
    DarkSeaGreen,
    DarkSlateBlue,
    DarkSlateGray,
    DarkSlateGrey,
    DarkTurquoise,
    DarkViolet,
    DeepPink,
    DeepSkyBlue,
    DimGray,
    DimGrey,
    DodgerBlue,
    FireBrick,
    FloralWhite,
    ForestGreen,
    Fuchsia,
    Gainsboro,
    GhostWhite,
    Gold,
    GoldenRod,
    Gray,
    Grey,
    Green,
    GreenYellow,
    HoneyDew,
    HotPink,
    IndianRed,
    Indigo,
    Ivory,
    Khaki,
    Lavender,
    LavenderBlush,
    LawnGreen,
    LemonChiffon,
    LightBlue,
    LightCoral,
    LightCyan,
    LightGoldenRodYellow,
    LightGray,
    LightGrey,
    LightGreen,
    LightPink,
    LightSalmon,
    LightSeaGreen,
    LightSkyBlue,
    LightSlateGray,
    LightSlateGrey,
    LightSteelBlue,
    LightYellow,
    Lime,
    LimeGreen,
    Linen,
    Magenta,
    Maroon,
    MediumAquaMarine,
    MediumBlue,
    MediumOrchid,
    MediumPurple,
    MediumSeaGreen,
    MediumSlateBlue,
    MediumSpringGreen,
    MediumTurquoise,
    MediumVioletRed,
    MidnightBlue,
    MintCream,
    MistyRose,
    Moccasin,
    NavajoWhite,
    Navy,
    OldLace,
    Olive,
    OliveDrab,
    Orange,
    OrangeRed,
    Orchid,
    PaleGoldenRod,
    PaleGreen,
    PaleTurquoise,
    PaleVioletRed,
    PapayaWhip,
    PeachPuff,
    Peru,
    Pink,
    Plum,
    PowderBlue,
    Purple,
    RebeccaPurple,
    Red,
    RosyBrown,
    RoyalBlue,
    SaddleBrown,
    Salmon,
    SandyBrown,
    SeaGreen,
    SeaShell,
    Sienna,
    Silver,
    SkyBlue,
    SlateBlue,
    SlateGray,
    SlateGrey,
    Snow,
    SpringGreen,
    SteelBlue,
    Tan,
    Teal,
    Thistle,
    Tomato,
    Turquoise,
    Violet,
    Wheat,
    White,
    WhiteSmoke,
    Yellow,
    YellowGreen,
}

impl Display for NamedColor {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            NamedColor::AliceBlue => write!(f, "aliceblue"),
            NamedColor::AntiqueWhite => write!(f, "antiquewhite"),
            NamedColor::Aqua => write!(f, "aqua"),
            NamedColor::Aquamarine => write!(f, "aquamarine"),
            NamedColor::Azure => write!(f, "azure"),
            NamedColor::Beige => write!(f, "beige"),
            NamedColor::Bisque => write!(f, "bisque"),
            NamedColor::Black => write!(f, "black"),
            NamedColor::BlanchedAlmond => write!(f, "blanchedalmond"),
            NamedColor::Blue => write!(f, "blue"),
            NamedColor::BlueViolet => write!(f, "blueviolet"),
            NamedColor::Brown => write!(f, "brown"),
            NamedColor::BurlyWood => write!(f, "burlywood"),
            NamedColor::CadetBlue => write!(f, "cadetblue"),
            NamedColor::Chartreuse => write!(f, "chartreuse"),
            NamedColor::Chocolate => write!(f, "chocolate"),
            NamedColor::Coral => write!(f, "coral"),
            NamedColor::CornflowerBlue => write!(f, "cornflowerblue"),
            NamedColor::Cornsilk => write!(f, "cornsilk"),
            NamedColor::Crimson => write!(f, "crimson"),
            NamedColor::Cyan => write!(f, "cyan"),
            NamedColor::DarkBlue => write!(f, "darkblue"),
            NamedColor::DarkCyan => write!(f, "darkcyan"),
            NamedColor::DarkGoldenRod => write!(f, "darkgoldenrod"),
            NamedColor::DarkGray => write!(f, "darkgray"),
            NamedColor::DarkGrey => write!(f, "darkgrey"),
            NamedColor::DarkGreen => write!(f, "darkgreen"),
            NamedColor::DarkKhaki => write!(f, "darkkhaki"),
            NamedColor::DarkMagenta => write!(f, "darkmagenta"),
            NamedColor::DarkOliveGreen => write!(f, "darkolivegreen"),
            NamedColor::DarkOrange => write!(f, "darkorange"),
            NamedColor::DarkOrchid => write!(f, "darkorchid"),
            NamedColor::DarkRed => write!(f, "darkred"),
            NamedColor::DarkSalmon => write!(f, "darksalmon"),
            NamedColor::DarkSeaGreen => write!(f, "darkseagreen"),
            NamedColor::DarkSlateBlue => write!(f, "darkslateblue"),
            NamedColor::DarkSlateGray => write!(f, "darkslategray"),
            NamedColor::DarkSlateGrey => write!(f, "darkslategrey"),
            NamedColor::DarkTurquoise => write!(f, "darkturquoise"),
            NamedColor::DarkViolet => write!(f, "darkviolet"),
            NamedColor::DeepPink => write!(f, "deeppink"),
            NamedColor::DeepSkyBlue => write!(f, "deepskyblue"),
            NamedColor::DimGray => write!(f, "dimgray"),
            NamedColor::DimGrey => write!(f, "dimgrey"),
            NamedColor::DodgerBlue => write!(f, "dodgerblue"),
            NamedColor::FireBrick => write!(f, "firebrick"),
            NamedColor::FloralWhite => write!(f, "floralwhite"),
            NamedColor::ForestGreen => write!(f, "forestgreen"),
            NamedColor::Fuchsia => write!(f, "fuchsia"),
            NamedColor::Gainsboro => write!(f, "gainsboro"),
            NamedColor::GhostWhite => write!(f, "ghostwhite"),
            NamedColor::Gold => write!(f, "gold"),
            NamedColor::GoldenRod => write!(f, "goldenrod"),
            NamedColor::Gray => write!(f, "gray"),
            NamedColor::Grey => write!(f, "grey"),
            NamedColor::Green => write!(f, "green"),
            NamedColor::GreenYellow => write!(f, "greenyellow"),
            NamedColor::HoneyDew => write!(f, "honeydew"),
            NamedColor::HotPink => write!(f, "hotpink"),
            NamedColor::IndianRed => write!(f, "indianred"),
            NamedColor::Indigo => write!(f, "indigo"),
            NamedColor::Ivory => write!(f, "ivory"),
            NamedColor::Khaki => write!(f, "khaki"),
            NamedColor::Lavender => write!(f, "lavender"),
            NamedColor::LavenderBlush => write!(f, "lavenderblush"),
            NamedColor::LawnGreen => write!(f, "lawngreen"),
            NamedColor::LemonChiffon => write!(f, "lemonchiffon"),
            NamedColor::LightBlue => write!(f, "lightblue"),
            NamedColor::LightCoral => write!(f, "lightcoral"),
            NamedColor::LightCyan => write!(f, "lightcyan"),
            NamedColor::LightGoldenRodYellow => write!(f, "lightgoldenrodyellow"),
            NamedColor::LightGray => write!(f, "lightgray"),
            NamedColor::LightGrey => write!(f, "lightgrey"),
            NamedColor::LightGreen => write!(f, "lightgreen"),
            NamedColor::LightPink => write!(f, "lightpink"),
            NamedColor::LightSalmon => write!(f, "lightsalmon"),
            NamedColor::LightSeaGreen => write!(f, "lightseagreen"),
            NamedColor::LightSkyBlue => write!(f, "lightskyblue"),
            NamedColor::LightSlateGray => write!(f, "lightslategray"),
            NamedColor::LightSlateGrey => write!(f, "lightslategrey"),
            NamedColor::LightSteelBlue => write!(f, "lightsteelblue"),
            NamedColor::LightYellow => write!(f, "lightyellow"),
            NamedColor::Lime => write!(f, "lime"),
            NamedColor::LimeGreen => write!(f, "limegreen"),
            NamedColor::Linen => write!(f, "linen"),
            NamedColor::Magenta => write!(f, "magenta"),
            NamedColor::Maroon => write!(f, "maroon"),
            NamedColor::MediumAquaMarine => write!(f, "mediumaquamarine"),
            NamedColor::MediumBlue => write!(f, "mediumblue"),
            NamedColor::MediumOrchid => write!(f, "mediumorchid"),
            NamedColor::MediumPurple => write!(f, "mediumpurple"),
            NamedColor::MediumSeaGreen => write!(f, "mediumseagreen"),
            NamedColor::MediumSlateBlue => write!(f, "mediumslateblue"),
            NamedColor::MediumSpringGreen => write!(f, "mediumspringgreen"),
            NamedColor::MediumTurquoise => write!(f, "mediumturquoise"),
            NamedColor::MediumVioletRed => write!(f, "mediumvioletred"),
            NamedColor::MidnightBlue => write!(f, "midnightblue"),
            NamedColor::MintCream => write!(f, "mintcream"),
            NamedColor::MistyRose => write!(f, "mistyrose"),
            NamedColor::Moccasin => write!(f, "moccasin"),
            NamedColor::NavajoWhite => write!(f, "navajowhite"),
            NamedColor::Navy => write!(f, "navy"),
            NamedColor::OldLace => write!(f, "oldlace"),
            NamedColor::Olive => write!(f, "olive"),
            NamedColor::OliveDrab => write!(f, "olivedrab"),
            NamedColor::Orange => write!(f, "orange"),
            NamedColor::OrangeRed => write!(f, "orangered"),
            NamedColor::Orchid => write!(f, "orchid"),
            NamedColor::PaleGoldenRod => write!(f, "palegoldenrod"),
            NamedColor::PaleGreen => write!(f, "palegreen"),
            NamedColor::PaleTurquoise => write!(f, "paleturquoise"),
            NamedColor::PaleVioletRed => write!(f, "palevioletred"),
            NamedColor::PapayaWhip => write!(f, "papayawhip"),
            NamedColor::PeachPuff => write!(f, "peachpuff"),
            NamedColor::Peru => write!(f, "peru"),
            NamedColor::Pink => write!(f, "pink"),
            NamedColor::Plum => write!(f, "plum"),
            NamedColor::PowderBlue => write!(f, "powderblue"),
            NamedColor::Purple => write!(f, "purple"),
            NamedColor::RebeccaPurple => write!(f, "rebeccapurple"),
            NamedColor::Red => write!(f, "red"),
            NamedColor::RosyBrown => write!(f, "rosybrown"),
            NamedColor::RoyalBlue => write!(f, "royalblue"),
            NamedColor::SaddleBrown => write!(f, "saddlebrown"),
            NamedColor::Salmon => write!(f, "salmon"),
            NamedColor::SandyBrown => write!(f, "sandybrown"),
            NamedColor::SeaGreen => write!(f, "seagreen"),
            NamedColor::SeaShell => write!(f, "seashell"),
            NamedColor::Sienna => write!(f, "sienna"),
            NamedColor::Silver => write!(f, "silver"),
            NamedColor::SkyBlue => write!(f, "skyblue"),
            NamedColor::SlateBlue => write!(f, "slateblue"),
            NamedColor::SlateGray => write!(f, "slategray"),
            NamedColor::SlateGrey => write!(f, "slategrey"),
            NamedColor::Snow => write!(f, "snow"),
            NamedColor::SpringGreen => write!(f, "springgreen"),
            NamedColor::SteelBlue => write!(f, "steelblue"),
            NamedColor::Tan => write!(f, "tan"),
            NamedColor::Teal => write!(f, "teal"),
            NamedColor::Thistle => write!(f, "thistle"),
            NamedColor::Tomato => write!(f, "tomato"),
            NamedColor::Turquoise => write!(f, "turquoise"),
            NamedColor::Violet => write!(f, "violet"),
            NamedColor::Wheat => write!(f, "wheat"),
            NamedColor::White => write!(f, "white"),
            NamedColor::WhiteSmoke => write!(f, "whitesmoke"),
            NamedColor::Yellow => write!(f, "yellow"),
            NamedColor::YellowGreen => write!(f, "yellowgreen"),
        }
    }
}
